# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tv_dataset = QtWidgets.QTableView(self.centralwidget)
        self.tv_dataset.setGridStyle(QtCore.Qt.DotLine)
        self.tv_dataset.setSortingEnabled(True)
        self.tv_dataset.setObjectName("tv_dataset")
        self.horizontalLayout.addWidget(self.tv_dataset)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSavePyrtemonnaieAs = QtWidgets.QMenu(self.menuFile)
        self.menuSavePyrtemonnaieAs.setObjectName("menuSavePyrtemonnaieAs")
        self.menuPyrtemonnaie = QtWidgets.QMenu(self.menubar)
        self.menuPyrtemonnaie.setEnabled(False)
        self.menuPyrtemonnaie.setObjectName("menuPyrtemonnaie")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setEnabled(False)
        self.menuReports.setObjectName("menuReports")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenPyrtemonnaie = QtWidgets.QAction(MainWindow)
        self.actionOpenPyrtemonnaie.setObjectName("actionOpenPyrtemonnaie")
        self.actionSavePyrtemonnaie = QtWidgets.QAction(MainWindow)
        self.actionSavePyrtemonnaie.setObjectName("actionSavePyrtemonnaie")
        self.actionSaveAsCsv = QtWidgets.QAction(MainWindow)
        self.actionSaveAsCsv.setObjectName("actionSaveAsCsv")
        self.actionSaveAsSqlite = QtWidgets.QAction(MainWindow)
        self.actionSaveAsSqlite.setObjectName("actionSaveAsSqlite")
        self.actionShowConfig = QtWidgets.QAction(MainWindow)
        self.actionShowConfig.setObjectName("actionShowConfig")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAddDatapoint = QtWidgets.QAction(MainWindow)
        self.actionAddDatapoint.setEnabled(True)
        self.actionAddDatapoint.setObjectName("actionAddDatapoint")
        self.actionEditDatapoint = QtWidgets.QAction(MainWindow)
        self.actionEditDatapoint.setObjectName("actionEditDatapoint")
        self.actionDeleteDatapoint = QtWidgets.QAction(MainWindow)
        self.actionDeleteDatapoint.setObjectName("actionDeleteDatapoint")
        self.actionShowPyrtemonnaie = QtWidgets.QAction(MainWindow)
        self.actionShowPyrtemonnaie.setObjectName("actionShowPyrtemonnaie")
        self.menuSavePyrtemonnaieAs.addAction(self.actionSaveAsCsv)
        self.menuSavePyrtemonnaieAs.addAction(self.actionSaveAsSqlite)
        self.menuFile.addAction(self.actionOpenPyrtemonnaie)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSavePyrtemonnaie)
        self.menuFile.addAction(self.menuSavePyrtemonnaieAs.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionShowConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuPyrtemonnaie.addAction(self.actionAddDatapoint)
        self.menuPyrtemonnaie.addAction(self.actionEditDatapoint)
        self.menuPyrtemonnaie.addAction(self.actionDeleteDatapoint)
        self.menuPyrtemonnaie.addSeparator()
        self.menuPyrtemonnaie.addAction(self.actionShowPyrtemonnaie)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPyrtemonnaie.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyrtemonnaie"))
        self.groupBox.setTitle(_translate("MainWindow", "Datensatz"))
        self.menuFile.setTitle(_translate("MainWindow", "Da&tei"))
        self.menuSavePyrtemonnaieAs.setTitle(_translate("MainWindow", "Pyrtemonnaie speichern als"))
        self.menuPyrtemonnaie.setTitle(_translate("MainWindow", "&Pyrtemonnaie"))
        self.menuReports.setTitle(_translate("MainWindow", "Beri&chte"))
        self.actionOpenPyrtemonnaie.setText(_translate("MainWindow", "Pyrtemonnaie öffnen"))
        self.actionSavePyrtemonnaie.setText(_translate("MainWindow", "Pyrtemonnaie speichern"))
        self.actionSaveAsCsv.setText(_translate("MainWindow", "csv"))
        self.actionSaveAsSqlite.setText(_translate("MainWindow", "sqlite"))
        self.actionShowConfig.setText(_translate("MainWindow", "Konfiguration anzeigen"))
        self.actionExit.setText(_translate("MainWindow", "Beenden"))
        self.actionAddDatapoint.setText(_translate("MainWindow", "Datenpunkt hinzufügen"))
        self.actionEditDatapoint.setText(_translate("MainWindow", "Datenpunkt bearbeiten"))
        self.actionDeleteDatapoint.setText(_translate("MainWindow", "Datenpunkt löschen"))
        self.actionShowPyrtemonnaie.setText(_translate("MainWindow", "Pyrtemonnaie anzeigen"))

